# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamMaster'),
            preserve_default=False,
        ),
    ]
