# Generated by Django 2.0.6 on 2018-06-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Timetable', '0001_initial'),
        ('Exam', '0001_initial'),
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examgrouproom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.Room'),
        ),
        migrations.AddField(
            model_name='examgroupdetail',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamDetail'),
        ),
        migrations.AddField(
            model_name='examgroupdetail',
            name='exam_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamGroup'),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamMaster'),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Semester'),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.YearBranch'),
        ),
    ]
