# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_auto_20180526_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetail',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamMaster'),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Semester'),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.YearBranch'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamDetail'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Subject'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.StudentSubject'),
        ),
    ]
