# Generated by Django 2.0.6 on 2018-06-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
        ('Exam', '0003_examsubjectroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectStudentRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_subject_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamSubjectRoom')),
                ('student_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.StudentSubject')),
            ],
        ),
    ]
