# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_room_capacity'),
        ('Exam', '0003_auto_20180604_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamGroupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamDetail')),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGroupRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamGroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.Room')),
            ],
        ),
    ]
