# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20180608_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
