# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_answer_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='score',
            new_name='negative_que_score',
        ),
        migrations.AddField(
            model_name='answer',
            name='positive_que_score',
            field=models.IntegerField(null=True),
        ),
    ]
