# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0004_auto_20180608_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='negative_que_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='positive_que_score',
            field=models.IntegerField(),
        ),
    ]
