# Generated by Django 2.0.6 on 2018-06-28 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('General', '0001_initial'),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFacultyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification', models.CharField(max_length=5000)),
                ('heading', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=200, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Division')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralStudentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification', models.CharField(max_length=5000)),
                ('heading', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=200, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('for_batch', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification', models.CharField(max_length=5000)),
                ('heading', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('has_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
