# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification', models.CharField(max_length=5000)),
                ('heading', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('has_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
