# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificnotification',
            old_name='type',
            new_name='heading',
        ),
    ]
