# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFacultyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification', models.CharField(max_length=5000)),
                ('heading', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=200, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralStudentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification', models.CharField(max_length=5000)),
                ('heading', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=200, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('for_batch', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
