# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificnotification',
            old_name='type',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='specificnotification',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specificnotification',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='specificnotification',
            name='action',
            field=models.CharField(default='', max_length=500),
        ),
    ]
