# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20180604_1330'),
        ('Dashboard', '0002_generalfacultynotification_generalstudentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfacultynotification',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch'),
            preserve_default=False,
        ),
    ]
