# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0028_auto_20180426_0036'),
        ('General', '0003_auto_20180527_0358'),
        ('Dashboard', '0002_generalfacultynotification_generalstudentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfacultynotification',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalfacultynotification',
            name='division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalstudentnotification',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch'),
        ),
        migrations.AddField(
            model_name='generalstudentnotification',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
    ]
