# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0028_auto_20180426_0036'),
        ('Dashboard', '0002_generalfacultynotification_generalstudentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfacultynotification',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch'),
            preserve_default=False,
        ),
    ]
