# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20180423_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificnotification',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specificnotification',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='specificnotification',
            name='action',
            field=models.CharField(default='', max_length=500),
        ),
    ]
