# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20180424_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificnotification',
            name='date',
            field=models.DateField(),
        ),
    ]
