# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_generalfacultynotification_branch'),
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfacultynotification',
            name='division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalstudentnotification',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch'),
        ),
        migrations.AddField(
            model_name='generalstudentnotification',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
    ]
