# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20180527_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalstudentnotification',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch'),
        ),
    ]
