# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_specificnotification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificnotification',
            name='date',
        ),
        migrations.AddField(
            model_name='specificnotification',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
