# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20180527_0343'),
        ('Dashboard', '0003_auto_20180527_0434'),
    ]

    operations = [
    ]
