# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_specificnotification_type'),
        ('Dashboard', '0002_auto_20180424_0244'),
    ]

    operations = [
    ]
