# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20180426_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificnotification',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='specificnotification',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
