# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20180426_0439'),
        ('Dashboard', '0006_auto_20180426_0357'),
    ]

    operations = [
    ]
