# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_merge_20180508_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificnotification',
            name='date',
        ),
    ]
