# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_merge_20180508_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificnotification',
            name='date',
        ),
        migrations.AlterField(
            model_name='specificnotification',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
