# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_schedulable_is_active'),
        ('Registration', '0028_auto_20180426_0036'),
        ('Dashboard', '0008_remove_specificnotification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFacultyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification', models.CharField(max_length=5000)),
                ('heading', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=200, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Division')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralStudentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification', models.CharField(max_length=5000)),
                ('heading', models.CharField(max_length=100)),
                ('action', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=200, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('for_batch', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Division')),
            ],
        ),
    ]
