# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_auto_20180508_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificnotification',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
