# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_merge_20180526_1802'),
        ('Dashboard', '0008_remove_specificnotification_date'),
    ]

    operations = [
    ]
