# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackupRestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='version',
            field=models.FloatField(unique=True),
        ),
    ]
