# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackupRestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('current_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackupRestore.Backup')),
            ],
        ),
    ]
