# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackupRestore', '0002_auto_20180526_1802'),
        ('BackupRestore', '0002_auto_20180508_1445'),
    ]

    operations = [
    ]
