# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='lectures_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='lectures_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
