# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinternship',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='studentinternship',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentinternship',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='studentinternship',
            name='work_from_home',
        ),
    ]
