# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbranch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
