# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0032_auto_20180604_0135'),
        ('Internship', '0002_auto_20180604_0135'),
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('elective_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.ElectiveSubject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_from_home', models.BooleanField(default=False)),
                ('application_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('internship', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Internship.Internship')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='electivegroup',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='electivegroup',
            name='year_branch',
        ),
        migrations.RemoveField(
            model_name='branchsubject',
            name='group',
        ),
        migrations.RemoveField(
            model_name='branchsubject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='yearsemester',
            name='year',
        ),
        migrations.AddField(
            model_name='collegeyear',
            name='no_of_semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='elective_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.ElectiveSubject'),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='has_registered_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='last_subject_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearsemester',
            name='lecture_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearsemester',
            name='lecture_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearsemester',
            name='year_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.YearBranch'),
        ),
        migrations.AlterField(
            model_name='collegeyear',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearsemester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearsemester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ElectiveGroup',
        ),
        migrations.AddField(
            model_name='electivebatch',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveDivision'),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='elective_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveDivision'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='elective_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveBatch'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='elective_division',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveDivision'),
        ),
    ]
