# Generated by Django 2.0.6 on 2018-07-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='year_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.YearBranch'),
        ),
    ]
