# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeyear',
            name='no_of_sem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='yearsemester',
            name='lecture_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='yearsemester',
            name='lecture_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='collegeyear',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
