# Generated by Django 2.0.6 on 2018-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeyear',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
