# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsubject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchsubject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchsubject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
