# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_auto_20180527_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeyear',
            old_name='no_of_sem',
            new_name='no_of_semester',
        ),
    ]
