# Generated by Django 2.0.6 on 2018-07-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_collegeyear_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsubject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='branchsubject',
            name='year_branch',
        ),
        migrations.AddField(
            model_name='branchsubject',
            name='year_semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='General.YearSemester'),
        ),
    ]
