# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_auto_20180123_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsubject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
