# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_collegeyear_no_of_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Semester')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.CollegeYear')),
            ],
        ),
    ]
