# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_auto_20180607_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternship',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinternship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentinternship',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinternship',
            name='work_from_home',
            field=models.BooleanField(default=False),
        ),
    ]
