# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_auto_20180527_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='semester1',
            new_name='semester',
        ),
    ]
