# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_auto_20180526_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeyear',
            name='no_of_semester',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
