# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('General', '0003_auto_20180123_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeyear',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
