# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_auto_20180527_0353'),
        ('General', '0003_auto_20180527_0358'),
    ]

    operations = [
    ]
