# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0032_auto_20180604_0135'),
        ('Internship', '0002_auto_20180604_0135'),
        ('General', '0003_auto_20180604_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_from_home', models.BooleanField(default=False)),
                ('application_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('internship', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Internship.Internship')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Student')),
            ],
        ),
    ]
