# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('General', '0004_auto_20170918_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='collegeextradetail',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Shift'),
        ),
    ]
