# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_collegeyear_no_of_semester'),
        ('General', '0004_auto_20180527_0035'),
    ]

    operations = [
    ]
