# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_schedulable_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulable',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
