# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_auto_20180527_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_electives', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Semester')),
                ('year_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.YearBranch')),
            ],
        ),
    ]
