# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_auto_20180210_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
    ]
