# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_merge_20180527_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_electives', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='collegeyear',
            name='no_of_semester',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='lectures_end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='lectures_start_date',
        ),
        migrations.AddField(
            model_name='branchsubject',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branchsubject',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electivegroup',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Semester'),
        ),
        migrations.AddField(
            model_name='electivegroup',
            name='year_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.YearBranch'),
        ),
    ]
