# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_auto_20180426_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
