# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_schedulable_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsubject',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branchsubject',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
