# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_auto_20180527_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeyear',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
