# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_schedulable_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysubject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
