# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_auto_20180210_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdivision',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
