# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0007_auto_20180527_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeyear',
            name='no_of_sem',
            field=models.IntegerField(null=True),
        ),
    ]
