# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0007_auto_20180526_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsubject',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
