# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0008_auto_20180219_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDivision',
            new_name='StudentDetail',
        ),
    ]
