# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0008_auto_20180527_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeyear',
            name='no_of_sem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegeyear',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
