# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0009_yearsemester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearsemester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearsemester',
            name='lecture_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearsemester',
            name='lecture_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearsemester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
