# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0009_auto_20180219_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='division',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch'),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='roll_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
