# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0010_auto_20180527_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electivegroup',
            name='number_of_electives',
        ),
        migrations.AddField(
            model_name='electivegroup',
            name='group',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yearsemester',
            name='number_of_electives',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchsubject',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveGroup'),
        ),
    ]
