# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0010_auto_20180527_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='lecture_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='lecture_start_date',
            field=models.DateField(null=True),
        ),
    ]
