# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0011_auto_20180219_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch'),
        ),
    ]
