# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0012_auto_20180527_1548'),
        ('General', '0004_merge_20180527_1452'),
    ]

    operations = [
    ]
