# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0012_auto_20180527_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearsemester',
            name='year',
        ),
        migrations.AddField(
            model_name='yearsemester',
            name='year_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.YearBranch'),
        ),
    ]
