# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_auto_20180527_1507'),
        ('General', '0013_merge_20180527_1612'),
    ]

    operations = [
    ]
