# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0014_merge_20180527_1622'),
        ('General', '0014_merge_20180527_1627'),
    ]

    operations = [
    ]
