# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0018_auto_20180528_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='has_registered_subject',
            field=models.BooleanField(default=False),
        ),
    ]
