# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0019_studentdetail_has_registered_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
