# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0020_auto_20180529_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivegroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
