# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0021_electivegroup_is_active'),
        ('General', '0020_auto_20180529_1136'),
    ]

    operations = [
    ]
