# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0022_merge_20180529_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='last_subject_registration_date',
            field=models.DateField(null=True),
        ),
    ]
