# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0023_studentdetail_last_subject_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='last_subject_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
