# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0021_auto_20180529_1143'),
        ('General', '0024_auto_20180529_1843'),
    ]

    operations = [
    ]
