# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0025_merge_20180529_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='division',
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='elective_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
    ]
