# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0026_auto_20180529_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Shift')),
                ('year_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.YearBranch')),
            ],
        ),
    ]
