# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0023_auto_20180530_1654'),
        ('General', '0027_electivedivision'),
    ]

    operations = [
    ]
