# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0028_merge_20180531_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivegroup',
            name='no_of_sub_to_choose',
            field=models.IntegerField(default=1),
        ),
    ]
