# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0029_auto_20180531_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsubject',
            name='group',
        ),
        migrations.RemoveField(
            model_name='branchsubject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='yearsemester',
            name='number_of_elective_groups',
        ),
    ]
