# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0034_auto_20180602_1503'),
        ('General', '0032_merge_20180601_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='electivegroup',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='electivegroup',
            name='year_branch',
        ),
        migrations.RemoveField(
            model_name='electivedivision',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='electivedivision',
            name='year_branch',
        ),
        migrations.AddField(
            model_name='electivedivision',
            name='elective_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.ElectiveSubject'),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='elective_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveDivision'),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='elective_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.ElectiveSubject'),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
        migrations.DeleteModel(
            name='ElectiveGroup',
        ),
        migrations.AddField(
            model_name='electivebatch',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveDivision'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='elective_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveBatch'),
        ),
    ]
