# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0032_auto_20180602_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivedivision',
            name='division',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
