# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0032_auto_20180604_0040'),
        ('Internship', '0002_auto_20180604_0040'),
        ('General', '0032_merge_20180603_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_from_home', models.BooleanField(default=False)),
                ('application_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('internship', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Internship.Internship')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='electivegroup',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='electivegroup',
            name='year_branch',
        ),
        migrations.RemoveField(
            model_name='electivedivision',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='electivedivision',
            name='year_branch',
        ),
        migrations.AddField(
            model_name='electivedivision',
            name='elective_subject',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='Registration.ElectiveSubject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='elective_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveDivision'),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='elective_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.ElectiveSubject'),
        ),
        migrations.AlterField(
            model_name='electivedivision',
            name='division',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
        migrations.DeleteModel(
            name='ElectiveGroup',
        ),
        migrations.AddField(
            model_name='electivebatch',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveDivision'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='elective_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveBatch'),
        ),
    ]
