# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0033_auto_20180603_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinternship',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='studentinternship',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentInternship',
        ),
    ]
