# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0033_auto_20180602_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivebatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='electivedivision',
            name='division',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='electivedivision',
            name='elective_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.ElectiveSubject'),
        ),
    ]
