# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0033_auto_20180603_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentinternship',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinternship',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentinternship',
            name='internship',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Internship.Internship'),
        ),
        migrations.AlterField(
            model_name='studentinternship',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Student'),
        ),
    ]
