# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0034_auto_20180603_0113'),
        ('General', '0034_auto_20180603_1247'),
    ]

    operations = [
    ]
