# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0004_internship'),
        ('Registration', '0033_auto_20180603_1441'),
        ('General', '0036_auto_20180603_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_from_home', models.BooleanField(default=False)),
                ('application_date', models.DateField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship.Internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Student')),
            ],
        ),
    ]
