# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0037_studentinternship'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternship',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentinternship',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Student'),
        ),
    ]
