# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0039_auto_20180603_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternship',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
