# Generated by Django 2.0.6 on 2018-07-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivesubject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
