# Generated by Django 2.0.6 on 2018-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivesubject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='initials',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
