# Generated by Django 2.0.6 on 2018-07-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20180708_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='initials',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
