# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch'),
        ),
    ]
