# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20170918_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='short_form',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
