# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 20:58
from __future__ import unicode_literals

import Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_auto_20170918_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='email',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='DOB',
            field=models.DateField(default='11/02/1976'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='current_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='current_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='current_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='current_pin_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='current_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=Registration.models.faculty_directory_path),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='doc_profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=Registration.models.faculty_directory_path),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emergency_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emergency_mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='father_designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='father_profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='mother_designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='mother_profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='projects',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
