# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_auto_20171213_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
