# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_auto_20170918_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='teaching_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
