# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 19:13
from __future__ import unicode_literals

import Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_auto_20171213_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='doc_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Registration.models.faculty_directory_path),
        ),
    ]
