# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_auto_20170918_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
