# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0005_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='year',
        ),
        migrations.AddField(
            model_name='hod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='start_date',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
