# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_auto_20170922_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
    ]
