# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_faculty_dob'),
        ('Registration', '0012_auto_20180123_2043'),
    ]

    operations = [
    ]
