# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0012_auto_20180123_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='DOB',
            field=models.DateField(blank=True, default='1996-02-11', null=True),
        ),
    ]
