# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0013_merge_20180123_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='DOB',
        ),
    ]
