# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0014_faculty_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
