# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0016_auto_20180206_0510'),
        ('Registration', '0015_auto_20180124_0730'),
        ('Registration', '0013_merge_20180123_2128'),
    ]

    operations = [
    ]
