# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0017_merge_20180208_1741'),
        ('Registration', '0017_merge_20180210_1517'),
    ]

    operations = [
    ]
