# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0018_merge_20180211_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRollNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Student')),
            ],
        ),
    ]
