# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0019_studentrollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
