# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0020_auto_20180211_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='initials',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
