# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0021_auto_20180214_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
