# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0024_auto_20180219_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
