# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0025_subject_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
    ]
