# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0026_remove_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='HOD',
        ),
    ]
