# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0028_auto_20180426_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_pattern',
            field=models.IntegerField(blank=True, default=2015),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
