# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0029_auto_20180527_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='elective_group',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
