# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0030_auto_20180529_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='elective_group',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
