# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0032_auto_20180531_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='elective_group',
        ),
    ]
