# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0032_auto_20180531_0115'),
        ('Registration', '0032_auto_20180531_0024'),
    ]

    operations = [
    ]
