# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0032_auto_20180531_0024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elective',
            new_name='ElectiveSubject',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='is_elective',
            new_name='is_elective_group',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='elective_group',
        ),
    ]
