# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0033_merge_20180602_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elective',
            new_name='ElectiveSubject',
        ),
    ]
