# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0034_auto_20180602_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='short_form',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
