# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0032_auto_20180531_0115'),
        ('Registration', '0034_auto_20180531_0047'),
    ]

    operations = [
    ]
