# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0035_merge_20180531_0154'),
        ('Registration', '0035_merge_20180601_1538'),
    ]

    operations = [
    ]
