# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
