# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0002_rolemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='rolemaster',
            old_name='role',
            new_name='role_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_role',
        ),
        migrations.AddField(
            model_name='role',
            name='role_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.RoleMaster'),
        ),
        migrations.AddField(
            model_name='role',
            name='user_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
