# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0002_rolemaster_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemaster',
            name='start_date',
            field=models.DateField(),
        ),
    ]
