# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0003_remove_user_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
