# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0003_auto_20180424_0128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='RoleManager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
