# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0003_auto_20180424_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemanager',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
