# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0004_auto_20170920_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
