# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('website', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
