# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0033_auto_20180603_1441'),
        ('Internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
