# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0002_auto_20180603_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
