# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0004_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='branch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch'),
        ),
    ]
