# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Registration', '0004_auto_20171005_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2017)),
                ('date', models.DateField(default=datetime.datetime(2017, 10, 18, 7, 44, 28, 670114))),
                ('type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('medium', models.CharField(max_length=50)),
                ('is_conference', models.BooleanField()),
                ('conference_attended', models.BooleanField()),
                ('level', models.CharField(max_length=50)),
                ('medium_name', models.CharField(max_length=200)),
                ('distribution', models.CharField(max_length=50)),
                ('peer_reviewed', models.BooleanField()),
                ('isbn', models.CharField(max_length=25)),
                ('impact_factor', models.FloatField()),
                ('volume', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('paper_with', models.CharField(max_length=20)),
                ('first_author', models.BooleanField()),
                ('funds_from_college', models.PositiveIntegerField()),
                ('other_info', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Faculty')),
            ],
        ),
    ]
