# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 18, 7, 46, 23, 878140, tzinfo=utc)),
        ),
    ]
