# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_auto_20171018_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 18, 7, 47, 41, 897304)),
        ),
    ]
