# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_auto_20171018_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 18, 15, 25, 5, 971208, tzinfo=utc)),
        ),
    ]
