# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_paper_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='other_info',
            field=models.TextField(),
        ),
    ]
