# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:44
from __future__ import unicode_literals

import Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_auto_20170925_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='list_of_files',
            field=models.FileField(blank=True, null=True, upload_to=Registration.models.faculty_directory_path),
        ),
    ]
