# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('Research', '0005_auto_20171018_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
