# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Research', '0007_auto_20171018_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='conference_attended',
            field=models.NullBooleanField(),
        ),
    ]
