# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Research', '0011_paper_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='Registration.Faculty'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(default=2018),
        ),
    ]
