# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0011_paper_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(default=2018),
        ),
    ]
