# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:11
from __future__ import unicode_literals

import Research.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_auto_20170922_1857'),
        ('Research', '0012_remove_paper_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Faculty'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=Research.models.faculty_papers_path),
        ),
    ]
