# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0033_auto_20180604_0040'),
        ('Registration', '0032_auto_20180604_0040'),
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='elective_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.ElectiveDivision'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='elective_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.ElectiveSubject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='division',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
    ]
