# Generated by Django 2.0.6 on 2018-06-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimetable',
            name='is_active',
        ),
    ]
