# Generated by Django 2.0.6 on 2018-07-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_rows',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Division'),
        ),
    ]
