# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Timetable', '0002_timetable_is_practical'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_substituted', models.BooleanField(default=False)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original',
                                               to='Timetable.Timetable')),
                ('substitute',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute',
                                   to='Timetable.Timetable')),
            ],
        ),
    ]
