# Generated by Django 2.0.6 on 2018-06-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_remove_datetimetable_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimetable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
