# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_auto_20180424_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='starting_tim',
            new_name='starting_time',
        ),
    ]
