# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimetable',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
