# Generated by Django 2.0.6 on 2018-06-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0003_datetimetable_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='lab',
            field=models.BooleanField(default=False),
        ),
    ]
