# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0003_datetimetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimetable',
            name='substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='Timetable.Timetable'),
        ),
    ]
