# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0005_auto_20170918_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='division',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
