# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_batch'),
        ('Timetable', '0007_auto_20170918_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='division',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='General.CollegeExtraDetail'),
        ),
    ]
