# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0008_auto_20171004_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='is_practical',
        ),
    ]
