# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_info',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='division',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='assignmentinfo',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='assignmentinfo',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='assignmentinfo',
            name='year',
        ),
        migrations.AddField(
            model_name='assignmentinfo',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.Batch'),
        ),
        migrations.AddField(
            model_name='assignmentinfo',
            name='complete_by',
            field=models.DateTimeField(default='2009-11-13T20:00+00:00'),
        ),
        migrations.AddField(
            model_name='assignmentinfo',
            name='issue_date',
            field=models.DateTimeField(default='2009-11-13T20:00+00:00'),
        ),
        migrations.AddField(
            model_name='assignmentinfo',
            name='plagiarism_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedassignment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmentinfo',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.FacultySubject'),
        ),
        migrations.AlterField(
            model_name='uploadedassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.AssignmentInfo'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
