# Generated by Django 2.0.6 on 2018-07-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Registration', '0002_auto_20180723_1919'),
        ('General', '0001_initial'),
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lectures', models.PositiveIntegerField()),
                ('attended_lectures', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='TotalAttendance',
        ),
    ]
