# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
        ('Attendance', '0002_facultyattendance_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Timetable.DateTimetable'),
        ),
    ]
