# Generated by Django 2.0.6 on 2018-07-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_auto_20180725_1949'),
        ('Attendance', '0003_auto_20180725_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlecture',
            name='year_semester',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='General.YearSemester'),
            preserve_default=False,
        ),
    ]
