# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_auto_20171213_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.Timetable'),
        ),
    ]
