# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Attendance', '0005_auto_20171213_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 22, 0, 41, 116342)),
        ),
    ]
