# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 22:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Attendance', '0006_auto_20171213_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 22, 2, 43, 592520)),
        ),
    ]
