# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0007_auto_20171213_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 14, 19, 13, 13, 750620)),
        ),
    ]
