# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Attendance', '0007_auto_20171213_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
