# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0008_auto_20171214_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 23, 15, 2, 50, 173457)),
        ),
    ]
