# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0009_auto_20180123_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 23, 15, 5, 55, 633519)),
        ),
    ]
