# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0018_merge_20180211_1012'),
        ('Attendance', '0011_auto_20180123_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lectures', models.PositiveIntegerField()),
                ('attended_leactures', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Subject')),
            ],
        ),
    ]
