# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Attendance', '0012_totalattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalattendance',
            old_name='attended_leactures',
            new_name='attended_lectures',
        ),
    ]
