# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0013_auto_20180211_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='date',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.DateTimetable'),
        ),
    ]
